Traceback (most recent call last):
  File "pkeylogger.py", line 45, in <module>
    input()
OSError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "pkeylogger.py", line 45, in <module>
    input()
OSError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "pkeylogger.py", line 48, in <module>
    run()
  File "pkeylogger.py", line 43, in run
    input()
OSError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "pkeylogger.py", line 48, in <module>
    run()
  File "pkeylogger.py", line 43, in run
    input()
OSError: [Errno 9] Bad file descriptor
